# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10y2-1WmBbklIs5TQa-uNTqJjFdRvZ8Ud
"""

import streamlit as st
import urllib.parse
from datetime import datetime

# App config
st.set_page_config(page_title="Laser Party Mission", page_icon="🎉", layout="centered")

# Custom CSS for fun animations and styling
st.markdown("""
<style>
    .stApp {
        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    }

    .main-title {
        font-size: 3rem;
        font-weight: bold;
        text-align: center;
        color: #ff6b6b;
        text-shadow: 2px 2px 4px rgba(0,0,0,0.3);
        animation: pulse 2s infinite;
    }

    @keyframes pulse {
        0% { transform: scale(1); }
        50% { transform: scale(1.05); }
        100% { transform: scale(1); }
    }

    .mission-box {
        background: linear-gradient(45deg, #ff6b6b, #4ecdc4);
        padding: 20px;
        border-radius: 15px;
        margin: 20px 0;
        box-shadow: 0 8px 16px rgba(0,0,0,0.2);
        animation: glow 3s ease-in-out infinite alternate;
    }

    @keyframes glow {
        from { box-shadow: 0 8px 16px rgba(0,0,0,0.2); }
        to { box-shadow: 0 8px 32px rgba(255,107,107,0.4); }
    }

    .laser-text {
        font-size: 1.5rem;
        font-weight: bold;
        color: #00ff00;
        text-shadow: 0 0 10px #00ff00;
        animation: laser-blink 1.5s infinite;
    }

    @keyframes laser-blink {
        0%, 50% { opacity: 1; }
        51%, 100% { opacity: 0.3; }
    }

    .commander-badge {
        background: linear-gradient(45deg, #ffd700, #ffed4a);
        padding: 10px 20px;
        border-radius: 25px;
        font-weight: bold;
        color: #333;
        text-align: center;
        margin: 10px 0;
        animation: bounce 2s infinite;
    }

    @keyframes bounce {
        0%, 20%, 50%, 80%, 100% { transform: translateY(0); }
        40% { transform: translateY(-10px); }
        60% { transform: translateY(-5px); }
    }
</style>
""", unsafe_allow_html=True)

# Initialize session state
if "stage" not in st.session_state:
    st.session_state.stage = "intro"
if "guest_name" not in st.session_state:
    st.session_state.guest_name = ""
if "quiz_answered" not in st.session_state:
    st.session_state.quiz_answered = False

# Stage: Introduction
if st.session_state.stage == "intro":
    st.markdown('<h1 class="main-title">🚀 LASER TAG MISSION 🚀</h1>', unsafe_allow_html=True)
    st.markdown('<div class="laser-text">⚡ TOP SECRET INVITATION ⚡</div>', unsafe_allow_html=True)

    st.image("https://i.imgur.com/s1N1cUe.png", use_container_width=True)

    st.markdown("""
    <div class="mission-box">
        <h2 style="text-align: center; color: white;">🎯 MISSION BRIEFING 🎯</h2>
        <p style="color: white; font-size: 1.2rem; text-align: center;">
            You have been selected for a TOP SECRET mission!<br>
            Do you have what it takes to join the elite laser squad?
        </p>
    </div>
    """, unsafe_allow_html=True)

    if st.button("🚀 ACCEPT MISSION", type="primary", use_container_width=True):
        st.session_state.stage = "chat"
        st.rerun()

# Stage: Enter Name
elif st.session_state.stage == "chat":
    st.markdown('<h2 style="text-align: center; color: #ff6b6b;">🎖️ AGENT REGISTRATION 🎖️</h2>', unsafe_allow_html=True)

    st.markdown("""
    <div class="mission-box">
        <div style="text-align: center; color: white; font-size: 1.3rem;">
            🤖 MISSION CONTROL: "State your name for the records, Agent!"
        </div>
    </div>
    """, unsafe_allow_html=True)

    name_input = st.text_input("🏷️ Enter your secret agent name:", value=st.session_state.guest_name, placeholder="Type your name here...")

    # Update session state guest_name only once without rerun
    if name_input != "" and st.session_state.guest_name == "":
        st.session_state.guest_name = name_input

    # Wait for user to submit name explicitly
    if st.button("✅ REGISTER AS AGENT", type="primary", use_container_width=True) and st.session_state.guest_name != "":
        st.session_state.stage = "mission_invite"
        st.rerun()

# Stage: Mission Invite
elif st.session_state.stage == "mission_invite":
    guest = st.session_state.guest_name

    st.markdown(f'<div class="commander-badge">🎖️ WELCOME AGENT {guest.upper()} 🎖️</div>', unsafe_allow_html=True)

    st.markdown(f"""
    <div class="mission-box">
        <h2 style="text-align: center; color: white;">🚨 URGENT MISSION ALERT 🚨</h2>
        <div style="color: white; font-size: 1.2rem; text-align: center;">
            <p><strong>Agent {guest}</strong>, we have a CODE RED situation!</p>
            <p>🎯 <strong>Mission Commander Alex</strong> needs backup!</p>
            <p>📅 <strong>Mission Date:</strong> Sunday, July 21st at 2:00 PM</p>
            <p>Will you answer the call?</p>
        </div>
    </div>
    """, unsafe_allow_html=True)

    col1, col2 = st.columns(2)
    if col1.button("⚡ YES! I'M READY FOR ACTION!", type="primary"):
        st.session_state.stage = "quiz"
        st.rerun()
    if col2.button("👨‍👩‍👧‍👦 I need parental clearance!", type="secondary"):
        st.info("🎖️ Roger that, Agent. Awaiting parental authorization...")

# Stage: Quiz
elif st.session_state.stage == "quiz":
    st.markdown('<h2 style="text-align: center; color: #ff6b6b;">🎯 AGENT TRAINING TEST 🎯</h2>', unsafe_allow_html=True)

    st.markdown("""
    <div class="mission-box">
        <div style="text-align: center; color: white; font-size: 1.2rem;">
            🔥 Before joining the elite squad, you must pass this test! 🔥
        </div>
    </div>
    """, unsafe_allow_html=True)

    st.markdown("### 🤔 **Training Question:**")
    st.markdown("**What color should a laser tag agent wear to stay hidden in the shadows?**")

    options = ["🌟 Bright Yellow", "💚 Neon Green", "🖤 Black", "🤍 White"]
    answer = st.radio("Choose your answer:", options, label_visibility="collapsed")

    if st.button("🔓 SUBMIT ANSWER", type="primary", use_container_width=True):
        if answer == "🖤 Black":
            st.success("🎉 CORRECT! You're ready for the mission, Agent!")
            st.balloons()
            st.session_state.quiz_answered = True
            st.session_state.stage = "invitation_card"
            st.rerun()
        else:
            st.error("❌ Not quite right! Try again, Agent!")
            st.markdown("💡 **Hint:** Think about what color helps you blend into dark places...")

# Stage: Invitation Card + RSVP
elif st.session_state.stage == "invitation_card":
    st.balloons()
    st.markdown(f'<h1 style="text-align: center; color: #ff6b6b;">🎉 MISSION ACCEPTED! 🎉</h1>', unsafe_allow_html=True)
    st.markdown(f'<div class="commander-badge">🏆 AGENT {st.session_state.guest_name.upper()} - MISSION APPROVED! 🏆</div>', unsafe_allow_html=True)

    st.markdown("""
    <div class="mission-box">
        <h2 style="text-align: center; color: white;">📋 MISSION DETAILS 📋</h2>
        <div style="color: white; font-size: 1.1rem;">
            <p>🗓️ <strong>Mission Date:</strong> Sunday, July 21st at 2:00 PM</p>
            <p>📍 <strong>HQ Location:</strong> <a href="https://www.google.com/maps?q=Laser+Quest+VR+Centre+Bromley+94+Bromley+Hill+Bromley+BR1+4JU" style="color: #4ecdc4;">Laser Quest & VR Centre Bromley<br>94 Bromley Hill, Bromley BR1 4JU</a></p>
            <p>👕 <strong>Uniform:</strong> Dark clothes (stealth mode activated!)</p>
            <p>🎒 <strong>Equipment:</strong> High energy, sneakers, and your biggest smile!</p>
        </div>
    </div>
    """, unsafe_allow_html=True)

    st.markdown('<h3 style="text-align: center; color: #4ecdc4;">📱 SEND MISSION RESPONSE 📱</h3>', unsafe_allow_html=True)
    st.markdown('<p style="text-align: center; color: white;">Complete the form below to confirm your mission status:</p>', unsafe_allow_html=True)

    with st.form("rsvp_form"):
        st.markdown("#### 🤖 Mission Status Report:")
        attending = st.radio("🎯 Will you join the mission?", ["✅ YES - I'm ready for action!", "❌ NO - Can't make it this time"])

        st.markdown("#### 🛡️ Special Agent Information:")
        allergies = st.text_area("⚠️ Any allergies or special requests?",
                                placeholder="Let us know about food allergies, medical conditions, or any special needs...",
                                help="This helps us keep all agents safe during the mission!")

        submitted = st.form_submit_button("🚀 SEND MISSION RESPONSE", type="primary", use_container_width=True)

        if submitted:
            # Create WhatsApp message
            attend_status = "YES" if "YES" in attending else "NO"
            whatsapp_message = f"""🎯 LASER TAG PARTY RSVP 🎯

Child: {st.session_state.guest_name}
Attending: {attend_status}
Allergies/Special Requests: {allergies if allergies else "None"}

Party Details:
📅 Sunday, July 21st at 2:00 PM
📍 Laser Quest & VR Centre Bromley, 94 Bromley Hill, Bromley BR1 4JU"""

            # Replace this with your actual WhatsApp number (international format, no +)
            # Example: UK number 07123456789 becomes 447123456789
            your_phone_number = "447555726983"  # ⚠️ REPLACE WITH YOUR ACTUAL NUMBER

            # Create WhatsApp URL with encoded message
            whatsapp_url = f"https://wa.me/{your_phone_number}?text={urllib.parse.quote(whatsapp_message)}"

            st.success("🎉 MISSION RESPONSE READY! 🎉")
            st.markdown("### 📱 Your response is ready to send!")

            # Show the message preview in a nice box
            st.markdown("""
            <div style="background: linear-gradient(45deg, #4ecdc4, #44a08d); padding: 15px; border-radius: 10px; margin: 15px 0;">
                <h4 style="color: white; text-align: center; margin: 0;">📋 MESSAGE PREVIEW</h4>
            </div>
            """, unsafe_allow_html=True)

            st.text_area("This message will be sent:", value=whatsapp_message, height=150, disabled=True)

            # WhatsApp button with better styling
            st.markdown("---")
            st.markdown('<h4 style="text-align: center; color: #4ecdc4;">🚀 LAUNCH WHATSAPP MESSENGER 🚀</h4>', unsafe_allow_html=True)
            st.markdown(f'''
            <div style="text-align: center; margin: 20px 0;">
                <a href="{whatsapp_url}" target="_blank" style="text-decoration: none;">
                    <button style="
                        background: linear-gradient(45deg, #25D366, #128C7E);
                        color: white;
                        padding: 20px 40px;
                        border: none;
                        border-radius: 50px;
                        font-size: 20px;
                        cursor: pointer;
                        font-weight: bold;
                        box-shadow: 0 8px 16px rgba(0,0,0,0.3);
                        transition: all 0.3s ease;
                        animation: pulse 2s infinite;
                    " onmouseover="this.style.transform='scale(1.05)'" onmouseout="this.style.transform='scale(1)'">
                        💬 SEND WHATSAPP RESPONSE
                    </button>
                </a>
            </div>
            ''', unsafe_allow_html=True)

            st.balloons()

            # Instructions with better styling
            st.markdown("""
            <div style="background: linear-gradient(45deg, #667eea, #764ba2); padding: 15px; border-radius: 10px; margin: 15px 0;">
                <p style="color: white; text-align: center; margin: 0;">
                    📱 <strong>MISSION INSTRUCTIONS:</strong> Click the button above to open WhatsApp with your response ready. Just tap 'Send' to complete your mission!
                </p>
            </div>
            """, unsafe_allow_html=True)

            # Backup option with emoji styling
            st.markdown("---")
            st.markdown('<h4 style="text-align: center; color: #ff6b6b;">🔧 BACKUP PROTOCOL 🔧</h4>', unsafe_allow_html=True)
            st.markdown("**If the auto-launch doesn't work:**")
            st.markdown("1. 📋 Copy the message above")
            st.markdown("2. 📱 Open WhatsApp manually")
            st.markdown(f"3. 📞 Send to: **+{your_phone_number[:2]} {your_phone_number[2:5]} {your_phone_number[5:8]} {your_phone_number[8:]}**")